name: traja
channels:
  - conda-forge
  - pytorch
dependencies:
  - ipython
  - pytorch-cpu
  - pip:
    - fastdtw
    - sphinx-gallery
    - sphinx_rtd_theme
  - pandas
  - numpy
  - matplotlib
  - shapely
  - scipy
  - sphinx
  - pillow
